Jira/csd 45670/dev/3.7.204.232
AgoraIO/Electron-SDK pull request #780
Opened 2022-06-23 11:08 UTC by sbd021

2022-06-23 15:40 UTC, zhangtao1104 commented on agora_node_ext/decode_data.cpp
> +  status = napi_invalid_arg;
这里 status 一直是 invalid，

2022-06-23 15:40 UTC, zhangtao1104 commented on ts/Api/native_type.ts
> +    framerate: number;
rate  native 也是小写吗？ C++ 要对齐

2022-06-23 15:40 UTC, zhangtao1104 commented on agora_node_ext/decode_data.cpp
> +  status = napi_invalid_arg;
status 一直是 invalid

2022-06-24 02:29 UTC, sbd021 commented on ts/Api/native_type.ts
> +    framerate: number;
native小写直接复制的

2022-06-24 06:50 UTC, LichKing-2234 requested changes

2022-06-24 06:50 UTC, LichKing-2234 commented on example/src/renderer/App.js
> +        framerate: 15,
这里是不是不能改？

2022-06-24 06:50 UTC, LichKing-2234 commented on agora_node_ext/decode_data.cpp
> +  if (status != napi_ok) {
这里需要删掉，不然每次都被return了

2022-06-24 10:59 UTC, closed without merging